domain: https://scarletlolocooking.com
url: https://scarletlolocooking.com

title: #The Scarlet Lolo Cooking Show# 
email: scarletlolocooking@gmail.com
author: Ms Scarlet

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
